---

- name: '[POSTINSTALL][LOGGING] Wait for operator to be ready'
  pause:
    seconds: 10

- name: '[POSTINSTALL][LOGGING] Setup Logging configuration'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition: "{{ lookup('template', 'logging-crd.yaml') }}"
