---

#https://docs.openshift.com/container-platform/4.3/authentication/identity_providers/configuring-htpasswd-identity-provider.html

- name: '[POST-OAUTH][HTPASSWD] Generate htpasswd hash for developer user'
  shell: >-
    htpasswd -nb developer "{{ ocp4_htpasswd_dev_password }}"|cut -d: -f2
  register: htpasswd_line
  when:
    - ocp4_htpasswd_dev_password is defined

- name: '[POST-OAUTH][HTPASSWD] Set fact for developer user password'
  set_fact:
    ocp4_htpasswd_dev_password: "{{ htpasswd_line.stdout }}"
  when:
    - ocp4_htpasswd_dev_password is defined
    - htpasswd_line is succeeded

- name: '[POST-OAUTH][HTPASSWD] Generate htpasswd hash for admin user'
  shell: >-
    htpasswd -nb admin "{{ ocp4_htpasswd_admin_password }}"|cut -d: -f2
  register: htpasswd_line
  when:
    - ocp4_htpasswd_admin_password is defined

- name: '[POST-OAUTH][HTPASSWD] Set fact admin user password'
  set_fact:
   ocp4_htpasswd_admin_password: "{{ htpasswd_line.stdout }}"
  when:
    - ocp4_htpasswd_admin_password is defined
    - htpasswd_line is succeeded

# TODO: '[POST-OAUTH] locate better the htpasswd
- name: '[POST-OAUTH][HTPASSWD] Generate htpasswd file'
  template:
    src: "htpasswd.j2"
    dest: "{{ user_path }}/users.htpasswd"
    owner: "{{ ansible_user }}"
    mode: 0664

- name: '[POST-OAUTH][HTPASSWD] Ensure htpasswd Secret is absent'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    api_version: v1
    kind: Secret
    name: htpasswd-secret
    namespace: openshift-config

- name: '[POST-OAUTH][HTPASSWD] Create htpasswd secret from htpasswd file'
  shell: "{{ user_path }}/tools/oc create secret generic htpasswd-secret -n openshift-config --from-file=htpasswd={{ user_path }}/users.htpasswd"
  environment:
    KUBECONFIG: "{{ user_path }}/auth/kubeconfig"

- name: '[POST-OAUTH][HTPASSWD] Update OAuth Configuration'
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('file', item ) | from_yaml }}"
  loop:
    - "{{ user_path }}/users.htpasswd"

#- name: '[POST-OAUTH][HTPASSWD] Create htpasswd secret from htpasswd file'
#  shell: "{{ container_dir }}/tools/oc adm add-cluster-role-to-user cluster-admin {{ ocp4_idm_admin_user }}"
#  environment:
#    KUBECONFIG: "{{ user_path }}/auth/kubeconfig"

- name: '[POST-OAUTH] Set up Cluster Admin User'
  when: ocp4_idm_admin_user is defined
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', './templates/cluster_role_binding.j2') | from_yaml }}"

- name: '[POST-OAUTH][HTPASSWD] Print User Information'
  debug:
    msg: "{{ item }}"
  loop:
  - "user.info: HTPasswd Authentication is enabled on this cluster."
  - "user.info: {{ ocp4_idm_htpasswd_user_base }}1 .. {{ ocp4_idm_htpasswd_user_base }}{{ ocp4_idm_htpasswd_user_count }} are created."
  - "user.info: User `{{ ocp4_idm_admin_user }}` is a cluster-admin"

# More Info: https://docs.openshift.com/container-platform/4.3/authentication/identity_providers/configuring-basic-authentication-identity-provider.html
